In [27]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rc
import tensorflow as tf
import tensorflow.distributions
from tensorflow.distributions import Dirichlet, Multinomial
from scipy.stats import entropy
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d, Axes3D
np.set_printoptions(suppress=True)

import data_handler as dh
import sinkhorn as skh
import oracles as oracle
import model as md
import time
import pickle

import os
import itertools

In [54]:
n = 2
i = 0

l = list(range(n))

In [55]:
l

[0, 1]

In [56]:
l.remove(0)

In [59]:
type(l)

list

In [226]:
d = {}
n = 2
corr_matrix = np.array([[0, 3200],[3200, 0]])

# for i in range(n): # targets

for i in range(1, n + 1): 
    d[i] = {}
    l = list(range(1, n + 1))
    l.remove(i)
    d[i]['targets'] = [i] + l
    l_2 = []
    
    for j, t in zip(range(1, n + 1), d[i]['targets']):
        value = corr_matrix[i-1][t-1]
        l_2.append(value)
        d[i]['corrs']= l_2

1 1
2 2
1 2
2 1


In [224]:
corr_matrix

array([[   0, 3200],
       [3200,    0]])

In [225]:
d

{1: {'targets': [1, 2], 'corrs': [0, 3200]},
 2: {'targets': [2, 1], 'corrs': [0, 3200]}}

In [248]:
rec = np.array([[0, 3000], [3000, 0]])
print(rec)

[[   0 3000]
 [3000    0]]


In [252]:
np.flip(rec, 1)

array([[3000,    0],
       [   0, 3000]])

In [238]:
n = 2
T = {(1, 1): 0.0, (1, 2): 0.5, (2, 2): 0.0, (2, 1): 0.5}
T_matrix = np.full((n, n), np.inf)

for key in T.keys():
    T_matrix[key[0] - 1][key[1] - 1] = T[key]
    print(key, T[key])
    print(type(key), type(T[key]))

(1, 1) 0.0
<class 'tuple'> <class 'float'>
(1, 2) 0.5
<class 'tuple'> <class 'float'>
(2, 2) 0.0
<class 'tuple'> <class 'float'>
(2, 1) 0.5
<class 'tuple'> <class 'float'>


In [239]:
T_matrix

array([[0. , 0.5],
       [0.5, 0. ]])